'''
Created on 20-JAN-2021

@author: Abishek Rajagopal
'''


"""
Django settings for ACCProject project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!vc3_zj)yp4fke24wan1289ap5)69t4fd@(el#uu(%a95tkd^!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
        'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_json_api',
    'SocialBookApp',
    'rest_framework.authtoken',
<<<<<<< HEAD
<<<<<<< HEAD
    'corsheaders',
    'treenode',
    'dbbackup',
    'django_crontab',
    
=======
    'treenode',

>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
=======
    'corsheaders',
    'treenode',
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765
]

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': str(BASE_DIR) + '/DBbackup/'}

CRONJOBS = [
            ('*/30 * * * *', 'ACCProject.cron.DB_backup_job')
            ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ACCProject.urls'

<<<<<<< HEAD
<<<<<<< HEAD
CORS_ORIGIN_ALLOW_ALL = True
=======
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '...',
    },
    'treenode': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}
>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
=======
CORS_ORIGIN_ALLOW_ALL = True
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'ACCProject.wsgi.application'
ASGI_APPLICATION = "ACCProject.asgi.application"
FERNET_KEYS = [
    "q^@n3ybwz%_w+4pqk_%rhz#_^vks-l^!&4)&-&+==ioag&lj5e"
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ],

}

CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
                'LOCATION': '...',
                                    },
                'treenode': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                 },
          }

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'Bookstagram-Database',

    }
}
# AUTH_USER_MODEL = 'SocialBookApp.App_User'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGGING_CONFIG = None

LOGGING = {

    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        }
    },

    'handlers': {
            'task': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(BASE_DIR) + '/logs/task.log',
                'formatter': 'verbose',
                'maxBytes': 5000000,
                'backupCount' : 2
            },
            'request': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(BASE_DIR) + '/logs/debugger.log',
                'formatter': 'verbose',
                'maxBytes': 5000000,
                'backupCount' : 2
            },
            'system': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(BASE_DIR) + '/logs/system.log',
                'formatter': 'verbose',
                'maxBytes': 5000000,
                'backupCount': 2
            },

        },

    'loggers': {

            'django': {
                'handlers': ['system'],
                'propagate': True,
            },

            'book.request': {
                'level': 'DEBUG',
                'handlers': ['request'],
                'propagate': True,
            },

            'book.task': {
                'level': 'DEBUG',
                'handlers': ['task'],
                'propagate': True,
            },


    }
}

import logging.config
logging.config.dictConfig(LOGGING)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CHANNEL_LAYERS = {
        "default": {
            
            "BACKEND":"channels_redis.core.RedisChannelLayer",
            "CONFIG":{
                
                "hosts": [("localhost",6379)]
                }
            }
        
        }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
