<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.2.18 on 2021-02-22 18:24
=======
# Generated by Django 3.1.5 on 2021-02-22 13:51
>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
=======
# Generated by Django 2.2.18 on 2021-02-22 18:24
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
<<<<<<< HEAD
=======
import django.utils.timezone
>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
=======
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765
import fernet_fields.fields
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('usertype', models.CharField(max_length=200)),
                ('password', fernet_fields.fields.EncryptedTextField(max_length=600)),
                ('country', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('friends', models.IntegerField(default=0)),
                ('wallet', models.IntegerField(default=500)),
                ('dp', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='App_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BookName', max_length=200)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('booktype', models.CharField(default='Text', max_length=200)),
                ('rate', models.FloatField(default=0.0)),
                ('stars', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('dp', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=500)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('authname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
=======
=======
                ('authname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765
            ],
        ),
        migrations.CreateModel(
            name='profileTXTPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
<<<<<<< HEAD
>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
            ],
        ),
        migrations.CreateModel(
            name='profileTXTPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
=======
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='TXTPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.profileTXTPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='profileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('chatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to='SocialBookApp.App_User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='OwnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Own', models.CharField(max_length=200)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=200)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to='SocialBookApp.App_User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='BookWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
            ],
        ),
        migrations.CreateModel(
            name='BookComments',
<<<<<<< HEAD
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
=======
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('usertype', models.CharField(max_length=200)),
                ('password', fernet_fields.fields.EncryptedTextField(max_length=600)),
                ('country', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('friends', models.IntegerField(default=0)),
                ('wallet', models.IntegerField(default=500)),
                ('dp', models.CharField(default='', max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TXTPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.profiletxtpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
            ],
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='profileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('chatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Own', models.CharField(max_length=200)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 456a87408c67465ab5351b43cc5e09ea0589d8d1
            ],
        ),
        migrations.CreateModel(
            name='friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=200)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.App_User')),
>>>>>>> 3a6ac2f4a60c403b47d2a717b96898550240b765
            ],
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
