# Generated by Django 2.2.18 on 2021-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='ratings',
            field=models.FloatField(default=5),
        ),
    ]
