# Generated by Django 3.1.5 on 2021-02-25 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialBookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='app_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='app_user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='App_User', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='authname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='bookcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='bookwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='ownbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='chatter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='profiletxtpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='txtpostcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
    ]
