# Generated by Django 3.1.5 on 2021-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0002_auto_20210225_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
