# Generated by Django 3.1.5 on 2021-03-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0003_booknewsfeed_booktreeconnect_bookusertree_friendnewsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownbook',
            name='referrer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='SocialBookApp.app_user'),
            preserve_default=False,
        ),
    ]
