# Generated by Django 3.1.5 on 2021-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0004_ownbook_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='dp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='dp',
            field=models.TextField(),
        ),
    ]
