# Generated by Django 3.1.5 on 2021-03-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0006_auto_20210312_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktree',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
            preserve_default=False,
        ),
    ]
