# Generated by Django 3.1.5 on 2021-03-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0007_booktree_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktree',
            name='Book',
        ),
    ]
