# Generated by Django 3.1.5 on 2021-03-18 23:32

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0007_commentsnewsfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXTPostCommentsNewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('PostWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostWriter', to='SocialBookApp.app_user')),
                ('Postuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Postuser', to='SocialBookApp.app_user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.profiletxtpost')),
            ],
        ),
    ]
