# Generated by Django 3.1.5 on 2021-03-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0008_remove_booktree_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktree',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
