# Generated by Django 3.1.5 on 2021-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0008_txtpostcommentsnewsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletxtpost',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
