# Generated by Django 3.1.5 on 2021-03-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0009_auto_20210312_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktree',
            old_name='mptt_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='booktree',
            name='UserName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
