# Generated by Django 3.1.5 on 2021-03-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0009_auto_20210324_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
