# Generated by Django 3.1.5 on 2021-03-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0010_auto_20210312_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTree',
        ),
    ]
