# Generated by Django 3.1.5 on 2021-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0010_auto_20210324_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
