# Generated by Django 3.1.5 on 2021-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0011_auto_20210324_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletxtpost',
            name='related',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiletxtpost',
            name='types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
