# Generated by Django 3.1.5 on 2021-04-02 20:37

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0012_auto_20210324_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTickerNewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Authjson', to='SocialBookApp.app_user')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookJson', to='SocialBookApp.book')),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuyerJson', to='SocialBookApp.app_user')),
            ],
        ),
    ]
