# Generated by Django 3.1.5 on 2021-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0013_booktickernewsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
