# Generated by Django 3.1.5 on 2021-03-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0015_auto_20210312_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookusertree',
            options={'ordering': ['tn_order'], 'verbose_name': 'BookUserTree', 'verbose_name_plural': 'BookUserTrees'},
        ),
    ]
