# Generated by Django 3.1.5 on 2021-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0016_auto_20210312_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookusertree',
            name='UserName',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
