# Generated by Django 3.1.5 on 2021-03-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0018_auto_20210312_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTreeConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tree', models.IntegerField(default=0)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
            ],
        ),
    ]
