# Generated by Django 3.1.5 on 2021-03-17 10:12

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0021_auto_20210313_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='dp',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CommentsNewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auth', to='SocialBookApp.app_user')),
                ('Bookcomments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.bookcomments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentyou', to='SocialBookApp.app_user')),
            ],
        ),
    ]
